
package com.ajaya.cashloan.cl.model.credit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirstCentralNigeriaWebServiceSoap", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirstCentralNigeriaWebServiceSoap {


    /**
     * Log in FirstCentral Nigeria WebService and returns a Ticket.
     * 
     * @param password
     * @param userName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Login", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/Login")
    @WebResult(name = "LoginResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "Login", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.LoginResponse")
    public String login(
        @WebParam(name = "UserName", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String userName,
        @WebParam(name = "Password", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String password);

    /**
     * Checks Validity of your FirstCentral Nigeria WebService Ticket.
     * 
     * @param firstCentralNigeriaWebServiceTicket
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "IsTicketValid", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/IsTicketValid")
    @WebResult(name = "IsTicketValidResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "IsTicketValid", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.IsTicketValid")
    @ResponseWrapper(localName = "IsTicketValidResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.IsTicketValidResponse")
    public boolean isTicketValid(
        @WebParam(name = "FirstCentralNigeriaWebServiceTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String firstCentralNigeriaWebServiceTicket);

    /**
     * Returns Full XML Nigeria for Consumer Matching based on ConsumerID.
     * 
     * @param identification
     * @param productID
     * @param dataTicket
     * @param enquiryReason
     * @param dateOfBirth
     * @param accountNumber
     * @param consumerName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConnectConsumerMatch", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/ConnectConsumerMatch")
    @WebResult(name = "ConnectConsumerMatchResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "ConnectConsumerMatch", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.ConnectConsumerMatch")
    @ResponseWrapper(localName = "ConnectConsumerMatchResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.ConnectConsumerMatchResponse")
    public String connectConsumerMatch(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "EnquiryReason", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String enquiryReason,
        @WebParam(name = "ConsumerName", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerName,
        @WebParam(name = "DateOfBirth", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dateOfBirth,
        @WebParam(name = "Identification", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String identification,
        @WebParam(name = "AccountNumber", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String accountNumber,
        @WebParam(name = "ProductID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String productID);

    /**
     * Returns Full XML Nigeria for Commercial Matching based on CommercialID.
     * 
     * @param productID
     * @param dataTicket
     * @param businessRegistrationNumber
     * @param businessName
     * @param enquiryReason
     * @param accountNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ConnectCommercialMatch", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/ConnectCommercialMatch")
    @WebResult(name = "ConnectCommercialMatchResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "ConnectCommercialMatch", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.ConnectCommercialMatch")
    @ResponseWrapper(localName = "ConnectCommercialMatchResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.ConnectCommercialMatchResponse")
    public String connectCommercialMatch(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "EnquiryReason", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String enquiryReason,
        @WebParam(name = "BusinessName", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String businessName,
        @WebParam(name = "BusinessRegistrationNumber", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String businessRegistrationNumber,
        @WebParam(name = "AccountNumber", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String accountNumber,
        @WebParam(name = "ProductID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String productID);

    /**
     * Returns Full XML Match based on Account Number.
     * 
     * @param dataTicket
     * @param accountNo
     * @param subscriberid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerAccountMatch", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerAccountMatch")
    @WebResult(name = "GetConsumerAccountMatchResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerAccountMatch", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerAccountMatch")
    @ResponseWrapper(localName = "GetConsumerAccountMatchResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerAccountMatchResponse")
    public String getConsumerAccountMatch(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "AccountNo", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String accountNo,
        @WebParam(name = "Subscriberid", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberid);

    /**
     * Returns Full XML Nigeria based on ConsumerID.
     * 
     * @param productID
     * @param dataTicket
     * @param consumerID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerEnquiryReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerEnquiryReport")
    @WebResult(name = "GetConsumerEnquiryReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerEnquiryReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerEnquiryReport")
    @ResponseWrapper(localName = "GetConsumerEnquiryReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerEnquiryReportResponse")
    public String getConsumerEnquiryReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "ProductID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String productID);

    /**
     * Returns Full XML Nigeria based on CommercialID.
     * 
     * @param commercialID
     * @param productID
     * @param dataTicket
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommercialEnquiryReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetCommercialEnquiryReport")
    @WebResult(name = "GetCommercialEnquiryReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetCommercialEnquiryReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialEnquiryReport")
    @ResponseWrapper(localName = "GetCommercialEnquiryReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialEnquiryReportResponse")
    public String getCommercialEnquiryReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "CommercialID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int commercialID,
        @WebParam(name = "ProductID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String productID);

    /**
     * Returns Full XML Nigeria for Consumer Basic Trace Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerBasicTraceReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerBasicTraceReport")
    @WebResult(name = "GetConsumerBasicTraceReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerBasicTraceReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicTraceReport")
    @ResponseWrapper(localName = "GetConsumerBasicTraceReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicTraceReportResponse")
    public String getConsumerBasicTraceReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Return Full XML Nigeria for X-Score Prime Report based on ConsumerID
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerXscorePrimereport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerXscorePrimereport")
    @WebResult(name = "GetConsumerXscorePrimereportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerXscorePrimereport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerXscorePrimereport")
    @ResponseWrapper(localName = "GetConsumerXscorePrimereportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerXscorePrimereportResponse")
    public String getConsumerXscorePrimereport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Return Full XML Nigeria for Prime Report based on ConsumerID
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerPrimeReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerPrimeReport")
    @WebResult(name = "GetConsumerPrimeReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerPrimeReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerPrimeReport")
    @ResponseWrapper(localName = "GetConsumerPrimeReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerPrimeReportResponse")
    public String getConsumerPrimeReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML Nigeria for Consumer Basic Credit Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerBasicCreditReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerBasicCreditReport")
    @WebResult(name = "GetConsumerBasicCreditReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerBasicCreditReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicCreditReport")
    @ResponseWrapper(localName = "GetConsumerBasicCreditReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicCreditReportResponse")
    public String getConsumerBasicCreditReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML for X-SCore Consumer Full Credit Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetXSCoreConsumerFullCreditReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetXSCoreConsumerFullCreditReport")
    @WebResult(name = "GetXSCoreConsumerFullCreditReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetXSCoreConsumerFullCreditReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetXSCoreConsumerFullCreditReport")
    @ResponseWrapper(localName = "GetXSCoreConsumerFullCreditReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetXSCoreConsumerFullCreditReportResponse")
    public String getXSCoreConsumerFullCreditReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML Nigeria for Consumer Full Credit Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetConsumerFullCreditReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerFullCreditReport")
    @WebResult(name = "GetConsumerFullCreditReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerFullCreditReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerFullCreditReport")
    @ResponseWrapper(localName = "GetConsumerFullCreditReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerFullCreditReportResponse")
    public String getConsumerFullCreditReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML Nigeria for Commercial Basic Credit Report based on CommercialID.
     * 
     * @param commercialMergeList
     * @param commercialID
     * @param dataTicket
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommercialBasicCreditReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetCommercialBasicCreditReport")
    @WebResult(name = "GetCommercialBasicCreditReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetCommercialBasicCreditReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialBasicCreditReport")
    @ResponseWrapper(localName = "GetCommercialBasicCreditReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialBasicCreditReportResponse")
    public String getCommercialBasicCreditReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "CommercialID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int commercialID,
        @WebParam(name = "commercialMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String commercialMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML Nigeria for Commercial Full Credit Report based on CommercialID.
     * 
     * @param commercialMergeList
     * @param commercialID
     * @param dataTicket
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommercialFullCreditReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetCommercialFullCreditReport")
    @WebResult(name = "GetCommercialFullCreditReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetCommercialFullCreditReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialFullCreditReport")
    @ResponseWrapper(localName = "GetCommercialFullCreditReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialFullCreditReportResponse")
    public String getCommercialFullCreditReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "CommercialID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int commercialID,
        @WebParam(name = "commercialMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String commercialMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Base 64 string for X-Score Consumer Full Credit Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetXSCoreConsumerFullCreditReportBinary", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetXSCoreConsumerFullCreditReportBinary")
    @WebResult(name = "GetXSCoreConsumerFullCreditReportBinaryResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetXSCoreConsumerFullCreditReportBinary", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetXSCoreConsumerFullCreditReportBinary")
    @ResponseWrapper(localName = "GetXSCoreConsumerFullCreditReportBinaryResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetXSCoreConsumerFullCreditReportBinaryResponse")
    public byte[] getXSCoreConsumerFullCreditReportBinary(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Base 64 string for Consumer Full Credit Report based on ConsumerID.
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetConsumerFullCreditReportBinary", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerFullCreditReportBinary")
    @WebResult(name = "GetConsumerFullCreditReportBinaryResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerFullCreditReportBinary", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerFullCreditReportBinary")
    @ResponseWrapper(localName = "GetConsumerFullCreditReportBinaryResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerFullCreditReportBinaryResponse")
    public byte[] getConsumerFullCreditReportBinary(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Base 64 string for Commercial Full Credit Report based on CommercialID.
     * 
     * @param commercialMergeList
     * @param commercialID
     * @param dataTicket
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetCommercialFullCreditReportBinary", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetCommercialFullCreditReportBinary")
    @WebResult(name = "GetCommercialFullCreditReportBinaryResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetCommercialFullCreditReportBinary", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialFullCreditReportBinary")
    @ResponseWrapper(localName = "GetCommercialFullCreditReportBinaryResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetCommercialFullCreditReportBinaryResponse")
    public byte[] getCommercialFullCreditReportBinary(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "CommercialID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int commercialID,
        @WebParam(name = "commercialMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String commercialMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Return Base 64 string for Consumer Basic Credit Report based on Consumerid
     * 
     * @param dataTicket
     * @param consumerID
     * @param consumerMergeList
     * @param subscriberEnquiryEngineID
     * @param enquiryID
     * @return
     *     returns byte[]
     */
    @WebMethod(operationName = "GetConsumerBasicCreditReportBinary", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetConsumerBasicCreditReportBinary")
    @WebResult(name = "GetConsumerBasicCreditReportBinaryResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetConsumerBasicCreditReportBinary", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicCreditReportBinary")
    @ResponseWrapper(localName = "GetConsumerBasicCreditReportBinaryResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetConsumerBasicCreditReportBinaryResponse")
    public byte[] getConsumerBasicCreditReportBinary(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "ConsumerID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int consumerID,
        @WebParam(name = "consumerMergeList", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String consumerMergeList,
        @WebParam(name = "SubscriberEnquiryEngineID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String subscriberEnquiryEngineID,
        @WebParam(name = "enquiryID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int enquiryID);

    /**
     * Returns Full XML for Consumer or Commercial Report based on EnquiryResultID.
     * 
     * @param dataTicket
     * @param subscriberEnquiryResultID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetReport", action = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/GetReport")
    @WebResult(name = "GetReportResult", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
    @RequestWrapper(localName = "GetReport", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetReport")
    @ResponseWrapper(localName = "GetReportResponse", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", className = "https.online_firstcentralcreditbureau_com.firstcentralnigeriawebservice.GetReportResponse")
    public String getReport(
        @WebParam(name = "DataTicket", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        String dataTicket,
        @WebParam(name = "SubscriberEnquiryResultID", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService")
        int subscriberEnquiryResultID);

}
