
package com.ajaya.cashloan.cl.model.credit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirstCentralNigeriaWebService", targetNamespace = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", wsdlLocation = "https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/FirstCentralNigeriaWebService.asmx?wsdl")
public class FirstCentralNigeriaWebService
    extends Service
{

    private final static URL FIRSTCENTRALNIGERIAWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRSTCENTRALNIGERIAWEBSERVICE_EXCEPTION;
    private final static QName FIRSTCENTRALNIGERIAWEBSERVICE_QNAME = new QName("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", "FirstCentralNigeriaWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService/FirstCentralNigeriaWebService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRSTCENTRALNIGERIAWEBSERVICE_WSDL_LOCATION = url;
        FIRSTCENTRALNIGERIAWEBSERVICE_EXCEPTION = e;
    }

    public FirstCentralNigeriaWebService() {
        super(__getWsdlLocation(), FIRSTCENTRALNIGERIAWEBSERVICE_QNAME);
    }

    public FirstCentralNigeriaWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRSTCENTRALNIGERIAWEBSERVICE_QNAME, features);
    }

    public FirstCentralNigeriaWebService(URL wsdlLocation) {
        super(wsdlLocation, FIRSTCENTRALNIGERIAWEBSERVICE_QNAME);
    }

    public FirstCentralNigeriaWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRSTCENTRALNIGERIAWEBSERVICE_QNAME, features);
    }

    public FirstCentralNigeriaWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstCentralNigeriaWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirstCentralNigeriaWebServiceSoap
     */
    @WebEndpoint(name = "FirstCentralNigeriaWebServiceSoap")
    public FirstCentralNigeriaWebServiceSoap getFirstCentralNigeriaWebServiceSoap() {
        return super.getPort(new QName("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", "FirstCentralNigeriaWebServiceSoap"), FirstCentralNigeriaWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstCentralNigeriaWebServiceSoap
     */
    @WebEndpoint(name = "FirstCentralNigeriaWebServiceSoap")
    public FirstCentralNigeriaWebServiceSoap getFirstCentralNigeriaWebServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", "FirstCentralNigeriaWebServiceSoap"), FirstCentralNigeriaWebServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FirstCentralNigeriaWebServiceSoap
     */
    @WebEndpoint(name = "FirstCentralNigeriaWebServiceSoap12")
    public FirstCentralNigeriaWebServiceSoap getFirstCentralNigeriaWebServiceSoap12() {
        return super.getPort(new QName("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", "FirstCentralNigeriaWebServiceSoap12"), FirstCentralNigeriaWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstCentralNigeriaWebServiceSoap
     */
    @WebEndpoint(name = "FirstCentralNigeriaWebServiceSoap12")
    public FirstCentralNigeriaWebServiceSoap getFirstCentralNigeriaWebServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://online.firstcentralcreditbureau.com/FirstCentralNigeriaWebService", "FirstCentralNigeriaWebServiceSoap12"), FirstCentralNigeriaWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRSTCENTRALNIGERIAWEBSERVICE_EXCEPTION!= null) {
            throw FIRSTCENTRALNIGERIAWEBSERVICE_EXCEPTION;
        }
        return FIRSTCENTRALNIGERIAWEBSERVICE_WSDL_LOCATION;
    }

}
